### ISSUE TITLE
File and path without extension

### ISSUE THREAD

**Issue by Ciantic** [emeraldwalk/vscode-runonsave#1]
Consider this:

`lessc C:/yada/somefile.less C:/yada/somefile.css`

At the moment there is no way to get the filename without extension. It's trivial to add when hacking the JS file.

**Comment by Ciantic** [comment]
Here is a patch:

```
cmdStr = cmdStr.replace(/\${fileNoExt}/g, path.join(path.dirname(document.fileName), path.basename(document.fileName, path.extname(document.fileName))));
```

Above ensures it works with any OS, I hope. It joins the dir and basename without extension.

**Comment by bmingles** [comment]
Added in 0.0.12 per https://github.com/emeraldwalk/vscode-runonsave/commit/30e0944642eee9c0e7f56c3325e283d0f1408699
