### ISSUE TITLE
confusion of "shell" configuration option

### ISSUE THREAD

**Issue by kagalle** [emeraldwalk/vscode-runonsave#10]
The "shell" configuration option had me confused becuase its hint text is:

> Specify shell path to run commands (gets used in options arg passed to child_process.exec).

I read this to mean that it set the working directory in which the command is run.  After reading the issue regarding shell, I realized it has to do with the actual shell the command is run in.
I was able to get the desired behavior for my particular use by writing the command as
`cd ${workspaceRoot} && npm run-script browserify`.
The hint might be edited to

> Specify the shell, including its path, in which to execute the command (gets used in options arg passed to child_process.exec).

**Comment by MartinMajewski** [comment]
Yeah, this confused me, too.

There should also be an placeholder to get the relative path to file from the current working directory after a `cd` command. Even better would be to specify a cwd.
I want to use run on save to avoid stupid gulp tasks for copying html files to by build directory, but it is a pain to preserve the current sub-path structure when the only path I can retrieve is the absolute path.

**Comment by bmingles** [comment]
@MartinMajewski Latest RunOnSave release added ${relativeFile} placeholder
