### ISSUE TITLE
{   "emeraldwalk.runonsave": {     "commands": [       {         // Run whenever any file is saved         "match": ".*",         "cmd": "echo '${fileBasename}' saved."       }     ]   } }

### ISSUE THREAD

**Issue by vishalkumar863** [emeraldwalk/vscode-runonsave#102]
{
  "emeraldwalk.runonsave": {
    "commands": [
      {
        // Run whenever any file is saved
        "match": ".*",
        "cmd": "echo '${fileBasename}' saved."
      }
    ]
  }
}

**Comment by vishalkumar863** [comment]
{
  "emeraldwalk.runonsave": {
    "commands": [
      {
        // Run whenever any file is saved
        "match": ".*",
        "cmd": "echo '${fileBasename}' saved."
      }
    ]
  }
}

**Comment by vishalkumar863** [comment]
{
  "emeraldwalk.runonsave": {
    "commands": [
      {
        // Run whenever any file is saved
        "match": ".*",
        "cmd": "echo '${fileBasename}' saved."
      }
    ]
  }
}

**Comment by bmingles** [comment]
@vishalkumar863 It’s not clear to me what this issue is about. Can you update the title and description to clarify?

**Comment by bmingles** [comment]
Closing this as it seems to have been created in error. @vishalkumar863 feel free to re-open with clearer details of what you are requesting.
