### ISSUE TITLE
${fileBasenameNoExtension} doesn't work

### ISSUE THREAD

**Issue by FrankSAURET** [emeraldwalk/vscode-runonsave#109]
**Describe the bug**
${fileBasenameNoExtension} is never repalce by the name of the file. Otehr like ${file} are working well.

**To Reproduce**

add something like this in tout setting.json and save your file. The name of saved file is ${fileBasenameNoExtension}.mo
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.pot$",
                "cmd": "msgfmt --check -o ${fileDirname}\\${fileBasenameNoExtension}.mo ${file}",
                }
            ]
        }

**Expected behavior**
Yhe name must be myfile.mo

**Screenshots**

**Version Info:**

**Additional context**

**Comment by FrankSAURET** [comment]
sorry it was ${fileBasenameNoExt}

**Comment by bmingles** [comment]
@FrankSAURET sounds like you figured it out. Can this issue be closed, or are you still experiencing issues?

**Comment by FrankSAURET** [comment]
It can be closed.
