### ISSUE TITLE
Bash command being appended to open file 

### ISSUE THREAD

**Issue by timsayshey** [emeraldwalk/vscode-runonsave#12]
Here are my settings: 
`// Place your settings in this file to overwrite the default settings
{
    "saveAndRun": {
        "commands": [
            {
                "match": ".go",
                "cmd": "echo `date` ${srcFile} > ./context/.build"
            }
        ]
    }
}`

It rebuilds my Docker container on save. But RunOnSave will randomly append "echo `date` ${srcFile} > ./context/.build" to my open file.

**Comment by bmingles** [comment]
Sorry for the late response on this. It looks like you are using an invalid placeholder ${srcFile}. See https://github.com/emeraldwalk/vscode-runonsave#placeholder-tokens for supported placeholders.
