### ISSUE TITLE
Local gulp not found

### ISSUE THREAD

**Issue by Robouste** [emeraldwalk/vscode-runonsave#14]
Hi, 

Trying to automate the sass compilation but I get this message : 
```
Running on save commands...
*** cmd start: gulp --no-color sass
[14:59:42] Local gulp not found in C:\Program Files (x86)\Microsoft VS Code
[14:59:42] Try running: npm install gulp
```

`gulp --no-color sass` works fine when done manually.

Gulp is installed globally

**Comment by bmingles** [comment]
If I had to guess vscode may not be aware of whatever environment variables make it globally visible. You could try `where gulp` to find the full path of the executable and then attempt using that.

**Comment by Robouste** [comment]
`where` is a linux command no ? I'm on windows

**Comment by bmingles** [comment]
`which` is the linux command. I believe`where` has been available on Windows for quite some time.

**Comment by bmingles** [comment]
Closing as this seems to be an environment specific issue.
