### ISSUE TITLE
formatting code requires re-opening file

### ISSUE THREAD

**Issue by victoroux** [emeraldwalk/vscode-runonsave#2]
Hi!

Great work so far. If I were to configure a task to format code on build, it will properly re-load the file I'm working on right in front of me. If I try to format "on-save" using this extension, it requires me to quickly ctrl-tab twice to reload the page.

Is this an extension issue or a problem with VS Code itself?

**Comment by MickVanDuijn** [comment]
Hi!

I have the same issue. It is still better than manually executing the command, but it would be nice if it could reload automatically. Still, great work :)

**Comment by bmingles** [comment]
I am looking into this one. Still haven't found anywhere in the vscode extension api to refresh a single file. I can reload vscode, but IMO it hurts the user experience to reload the application on every file save.

**Comment by mattetti** [comment]
encountered the same issue here

**Comment by bmingles** [comment]
I have an issue opened with the vscode team to explore how to fix this https://github.com/Microsoft/vscode/issues/7532

**Comment by bmingles** [comment]
Still doesn't appear to be an api for this as microsoft/vscode#7532 is still open. Closing for now until I hear otherwise.
