### ISSUE TITLE
Multiple subfolders with the same name, in a single workspace

### ISSUE THREAD

**Issue by Jelmer7** [emeraldwalk/vscode-runonsave#21]
I'm working in a workspace with 2 main folders with similar structure. I want to use your extension on one of the folders for automatically syncronizing files on my development environment.
Structure looks like this:
mainfolder1/templates/<template files i want to sync>
mainfolder2/templates/<template files i dont want to sync>
my workspace settings look like this:

```
"emeraldwalk.runonsave": {
    "commands": [
        {
	    "match": "mainfolder1\\templates\\.*",
	    "cmd": "ROBOCOPY ${fileDirname} <development location> ${fileBasename} /is /it",
        }
    ]
}
```
It doesnt work when i use this. It does work when i use:
`""match": "templates\\.*",`
but in both template folders (mainfolder2 too).
Is there any way to make this work while still working in a multi folder workspace?

**Comment by Jelmer7** [comment]
The extension has problems working with multiple sub folders.
`"match": "templates\\test\\.*"` also does not work properly.
It wil not run the command inside the test folder, using `"match": "templates\\.*"` it obviously works.

To clearify: The problem is not limited to main workspace folders, or however they're called in VSCode. The extension can't deal with subfolders.

**Comment by bmingles** [comment]
I think your Regex might be off due to the need to double escape backslashes when in a JSON string. Assuming you are targetting `templates\test.*` you need `"match": "templates\\\\test\\.*"`. The javascript string value that will actually be used in the Regex will be `templates\\test\.*`

**Comment by Jelmer7** [comment]
My bad, sorry!
