### ISSUE TITLE
Support for Multi-root Workspaces

### ISSUE THREAD

**Issue by Henk3000** [emeraldwalk/vscode-runonsave#22]
I'm working with multi root workspaces and I am not able to get the folder root path in my command.

I would like to use something like "${workspaceFolder}" like is mentioned on the [variable reference of vscode](https://code.visualstudio.com/docs/editor/variables-reference).

Can it be added or is there another way this can be achieved?

**Comment by bmingles** [comment]
I'm starting to look into this now.

**Comment by bmingles** [comment]
5826336b485b6bb13fbb3e14d03e651f54dae348

**Comment by bmingles** [comment]
1ccd7ec0bf4463caa7749a7c0c815714aff7b21a

**Comment by bmingles** [comment]
f100db852a7de9cc7e366cf9447c3943e594e979

**Comment by bmingles** [comment]
Released in 0.1.0
