### ISSUE TITLE
Need additional Placeholder Tokens: relativeFile, workspaceRootDirname

### ISSUE THREAD

**Issue by siliond** [emeraldwalk/vscode-runonsave#23]
I needed some **extra placeholder tokens** to _be able to copy files to secondary location_, server, upon save:

- relativeFile
- workspaceRootDirname

Code changes: extension.ts line 169
``            cmdStr = cmdStr.replace(/\${relativeFile}/g, `${path.normalize(path.relative(vscode.workspace.rootPath, document.fileName))}`);
            cmdStr = cmdStr.replace(/\${workspaceRootDirname}/g, `${path.basename(vscode.workspace.rootPath)}`);``

Example configuration:
`"emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.js$",
                "cmd": "if exist \"\\\\server\\Web\\${workspaceRootDirname}\\${relativeFile}\" copy /Y \"${file}\" \"\\\\server\\Web\\${workspaceRootDirname}\\${relativeFile}\""
            }
        ]
    }`

**Comment by bmingles** [comment]
${workspaceFolder} and ${relativeFile} tokens have been added and released in 0.1.0

4cb4859dc760b9f5e1bfc45c3836d3398ea4027d
5826336b485b6bb13fbb3e14d03e651f54dae348
1ccd7ec0bf4463caa7749a7c0c815714aff7b21a
