### ISSUE TITLE
node should be a dev dependency?

### ISSUE THREAD

**Issue by swiffer** [emeraldwalk/vscode-runonsave#24]
shouldn't node be a dev dependency?

from the docs: https://code.visualstudio.com/api/get-started/extension-anatomy

```
	"devDependencies": {
		"@types/node": "^8.10.25",
		"tslint": "^5.11.0",
		"typescript": "^2.6.1",
		"vscode": "^1.1.22"
	}
```

**Comment by bmingles** [comment]
Technically it probably should, although it's only the typings for node and not actually node, so not a super high priority IMO. Feel free to submit a PR if you'd like. I would accept the change.
