### ISSUE TITLE
Where is the output of the "Run on Save" command displayed?

### ISSUE THREAD

**Issue by userlerueda** [emeraldwalk/vscode-runonsave#48]
I would like to see the output of the command it executed on save, is that possible?

**Comment by paxcodes** [comment]
I was wondering that myself, too. I think I found it:

Output > Then on the Dropdown on the left, select `Run on Save`

![community_css_—_topanswers_local](https://user-images.githubusercontent.com/13646646/83331095-bcf8fa00-a248-11ea-80bb-24bfd990f759.png)

**Comment by bmingles** [comment]
Yes, this is available in the Output pane > Run on Save dropdown item
