### ISSUE TITLE
Feature request: Support actions on saving Jupyter Notebooks

### ISSUE THREAD

**Issue by francisco-perez-sorrosal** [emeraldwalk/vscode-runonsave#57]
For VSCode to support that, it requires to expose new events. I created an [issue in the VSCode github repo](https://github.com/microsoft/vscode/issues/130799) for that. Please upvote there!

**Comment by javiercmh** [comment]
I did, I hope they do it!!

**Comment by nonoash** [comment]
Seems like it didn't get enough upvotes, pity

**Comment by nanne-aben** [comment]
Seems like they have implemented it now! As far as I can tell, it's not yet implemented in runonsave though. Is that correct? Any plans for adding this?

I'd love to use this in combination with [nbqa](https://github.com/nbQA-dev/nbQA).

**Comment by mfolkestad** [comment]
Would be great to get this feature!

**Comment by CS-Account** [comment]
A PR addressing this issue has been created: #107
