### ISSUE TITLE
${file} and ${fileDirname} don't work for me

### ISSUE THREAD

**Issue by kev23777** [emeraldwalk/vscode-runonsave#6]
${fileBasename} works fine

If my config is this

  "emeraldwalk.runonsave": {
    "commands": [
      {
        "match": "\\.ts$",
        "cmd": "echo 'I am ${fileBasename}.'"
      }
    ]
  }

It echos in the footer of VS Code

***cmd start: echo 'I am filename.ts'

but if I change the cmd line to

"cmd": "echo 'I am ${file}.'"

Nothing happens on save.

I'm using VS Code 1.3 on Windows 7 64 bit

**Comment by bmingles** [comment]
@kev23777 Can you verify what version of the RunOnSave extension is installed?

**Comment by kev23777** [comment]
v0.0.14 is what installed from the extension manager in VS Code 1.3

**Comment by kev23777** [comment]
Just noticed that this has been fixed. Thank you very much!
