### ISSUE TITLE
Escaping spaces in file path

### ISSUE THREAD

**Issue by xandr2** [emeraldwalk/vscode-runonsave#68]
I found a bug when the path to the file has spaces it produces an error no such file or directory.
Log example:
```
Running on save commands...
*** cmd start: terragrunt hclfmt --terragrunt-hclfmt-file /path/to/my/project/budgets/Monthly payments budget/terragrunt.hcl
time=2022-05-16T20:37:45+03:00 level=error msg=Error retrieving file info of /path/to/my/project/budgets/Monthly
time=2022-05-16T20:37:45+03:00 level=error msg=stat /path/to/my/projectbudgets/Monthly: no such file or directory
time=2022-05-16T20:37:45+03:00 level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
Run on Save done.
Run On Save: Reloading config.
```

As I found it can be fixed with .replace function like that `.replace(/(?=[ ])/g, '\\');` but I don't know TypeScript and what I should change on code (
Can you, please, make a fix for that problem?

**Comment by oxilor** [comment]
Variables shouldn't escape spaces. If a variable ($PATH, $file, whatever) contains the space character, just enclose it in quotation marks (`"`).
```
"cmd": "terragrunt hclfmt --terragrunt-hclfmt-file \"${file}\""
```
