### ISSUE TITLE
RESOLVED: full path now needed for all programs to run 

### ISSUE THREAD

**Issue by aubuchcl** [emeraldwalk/vscode-runonsave#77]
Was working, but now seems to need the absolute path to all programs in order to run..

**Comment by aubuchcl** [comment]
READ HERE FOR RESOLUTION 

If you're like me and you run ohmyzsh on mac with powerline 10k and you have not updated in a while, there is a case where most programs on your machine would run normally but run on save would fail to load any executables without the full path to such executable.  

It seems as though updating oh my zsh and p10k solved whatever intermediary issue was causing the PATH to not be read properly.  

If you're having this issue and you dont use this exact setup consider running echo $PATH on your machine (on save) as this is what gave me the hint to update oh my zsh and p10k.

**Comment by basepi** [comment]
@aubuchcl thanks for the tip! I had the same problem, and updating worked for me too.

**Comment by bmingles** [comment]
Glad you got it working
