### ISSUE TITLE
README: add info how to see the logs

### ISSUE THREAD

**Issue by d9k** [emeraldwalk/vscode-runonsave#84]
Hello! 
Add info how to see the logs to the README for new VS Code users:

`cmd-shift-p` -> Search `Developer: Show Logs` -> `Extension Host`, then select `Run on Save` in drop-down list on upper-right :arrow_upper_right: corner

**Comment by bmingles** [comment]
This was recently added to the README. Also planning on making some changes on how this works, so going to close this.
