### ISSUE TITLE
File editor does't always refresh after command

### ISSUE THREAD

**Issue by pruizFocusrite** [emeraldwalk/vscode-runonsave#88]
I use VSCode v1.89.1 and RunOnSave v0.2.0, with this minimal `.vscode/settings.json`:
```
{
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.cpp$",
                "cmd": "clang-format -i ${file}"
            }
        ]
    }
}
```

I have the following file tree in VSCode:
```
.
|-- foo.cpp
|-- src
|   |-- bar.cpp
|   |-- main
|   |   -- foobar.cpp
```

Saving the top-level `foo.cpp` formats the file and, crucially, refreshes the open editor in thte GUI (as expected).

Saving any of the `.cpp` files in the sub-directories also formats the file **but does not refresh the display**. (Trying to save again brings up the dirty file [conflict resolution popup](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_42.md#save-conflict-resolution)). Bringing another file forefront in the GUI, and then the problematic file back again does refresh it from disk.

As a workaround, I also tried `"cmd": "clang-format -i ${file}; code -r ${file}"` but that made no difference.

**Comment by bmingles** [comment]
@pruizFocusrite the extension doesn’t actually do anything to refresh editors. The fact that it refreshes in some cases would suggest some other on save formatting maybe running. The VS code docs would suggest clang-format is a built in formatter already.
https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting 
Is it possible multiple formatters are running when you save your files?
