### ISSUE TITLE
patch won't work in cmd

### ISSUE THREAD

**Issue by softshape** [emeraldwalk/vscode-runonsave#9]
Hi all,

here's my config:

```
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "index.local.html",
                "cmd": "patch --binary -i C:/Work/index.diff.txt -o C:/Work/index.html"
            }
        ]
    }
```

patch is the command-line tool coming with Git for Windows. The command is working fine when I run it from command line. But when I save index.local.html, I get index.html with zero size.

How to fix that?

**Comment by bmingles** [comment]
Can you confirm if the command is actually running on save? I just want to verify that the match is working.

**Comment by softshape** [comment]
It works silently, but 1) it does create an output file, just it's empty, and 2) 'Run on Save done' appears in the status bar.

**Comment by softshape** [comment]
I've found the reason! It was because of undefined working directory. I wrapped patch to batch-file and added cd C:\Work\ line before patch, and it works now!
