### ISSUE TITLE
Future of emaraldwalk/vscode-runonsave

### ISSUE THREAD

**Issue by sm11963** [emeraldwalk/vscode-runonsave#91]
Hello @bmingles, it looks like this repo has built up a number of issues and several PRs over the years. Any plans to continue to maintain this extension? 

Seems like its been useful to many people, but also there is a lot to be added (I have my own requests that I was about to add to this list). If this isn't in active maintainance, maybe it would be best to direct folks to start a new main fork or use something else already out there? Perhaps https://github.com/pucelle/vscode-run-on-save? (just found this myself and haven't actually tried it yet)

**Comment by bmingles** [comment]
@sm11963 I’m trying to catch up on the backlog. It’s honestly been kind of out of sight out of mind due to my GitHub notifications being misconfigured, but trying to get back on top of it.

I’ve not used any other run-on save extensions, so I would not be inclined to recommend any particular ones.

**Comment by sm11963** [comment]
Sounds good! Just wanted to start a conversation on the plan. Feel free to close this out since it sounds like you’ll be going through the backlog now.

Btw I have been using https://github.com/pucelle/vscode-run-on-save since this post and it’s been working well for my needs. The major feature I was missing from this one was opening the output when an error occurred in the background.

**Comment by bmingles** [comment]
Meaning, auto show the “Run on Save” panel if it has an error code,

**Comment by sm11963** [comment]
Yup! Or some other way to indicate there was an error that needs to be addressed. 

I’m using run on save to trigger TS and SCSS compilation and had a few instances where I was scratching my head when things weren’t updating due to an error in the compilation.

**Comment by oNaiPs** [comment]
+1 on @sm11963 request. I would be willing to implement and create PR if you agree on the feature@bmingles

**Comment by bmingles** [comment]
@oNaiPs  [97-output-improvements](https://github.com/emeraldwalk/vscode-runonsave/tree/97-output-improvements) has merged, so can base new work on main again

**Comment by bmingles** [comment]
Closing. Feel free to raise specific feature requests as new issues.

**Comment by sm11963** [comment]
Awesome, this is great to see! Thanks!
