### ISSUE TITLE
Output improvements

### ISSUE THREAD

**Issue by bmingles** [emeraldwalk/vscode-runonsave#97]
There are a number of requests that have been made for better output configuration: 
e.g.
- [Add option to remove header and footer messages #89](https://github.com/emeraldwalk/vscode-runonsave/issues/89)
- [Add configuration options for status messages #83](https://github.com/emeraldwalk/vscode-runonsave/pull/83)

I'd like to address this holistically:
- Use integrated terminal instead of output channel for primary output
- Better control over output

**Comment by vishalkumar863** [comment]
{
  "emeraldwalk.runonsave": {
    "commands": [
      {
        // Run whenever any file is saved
        "match": ".*",
        "cmd": "echo '${fileBasename}' saved."
      }
    ]
  }
}

**Comment by bmingles** [comment]
Merged
